// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: geocode.proto

package geocode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Geocoder_Search_FullMethodName         = "/geocode.Geocoder/Search"
	Geocoder_GeocodeAddress_FullMethodName = "/geocode.Geocoder/GeocodeAddress"
)

// GeocoderClient is the client API for Geocoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeocoderClient interface {
	Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GeocodeAddress(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
}

type geocoderClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocoderClient(cc grpc.ClientConnInterface) GeocoderClient {
	return &geocoderClient{cc}
}

func (c *geocoderClient) Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Geocoder_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocoderClient) GeocodeAddress(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, Geocoder_GeocodeAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocoderServer is the server API for Geocoder service.
// All implementations must embed UnimplementedGeocoderServer
// for forward compatibility
type GeocoderServer interface {
	Search(context.Context, *Request) (*Response, error)
	GeocodeAddress(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	mustEmbedUnimplementedGeocoderServer()
}

// UnimplementedGeocoderServer must be embedded to have forward compatible implementations.
type UnimplementedGeocoderServer struct {
}

func (UnimplementedGeocoderServer) Search(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGeocoderServer) GeocodeAddress(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeocodeAddress not implemented")
}
func (UnimplementedGeocoderServer) mustEmbedUnimplementedGeocoderServer() {}

// UnsafeGeocoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeocoderServer will
// result in compilation errors.
type UnsafeGeocoderServer interface {
	mustEmbedUnimplementedGeocoderServer()
}

func RegisterGeocoderServer(s grpc.ServiceRegistrar, srv GeocoderServer) {
	s.RegisterService(&Geocoder_ServiceDesc, srv)
}

func _Geocoder_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocoderServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocoder_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocoderServer).Search(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocoder_GeocodeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocoderServer).GeocodeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocoder_GeocodeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocoderServer).GeocodeAddress(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Geocoder_ServiceDesc is the grpc.ServiceDesc for Geocoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Geocoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geocode.Geocoder",
	HandlerType: (*GeocoderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Geocoder_Search_Handler,
		},
		{
			MethodName: "GeocodeAddress",
			Handler:    _Geocoder_GeocodeAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geocode.proto",
}
